<!-- This is the LeaseHood in your hood page; it discusses how Leasehood gives back to its community. -->

<?php
        $title = "LeaseHood in Your 'Hood";
	include 'Header.php';
?>
<div id="maincontent">
<h1 class="Title">LeaseHood in Your 'Hood</h1>
<p>
    LeaseHood recognizes that if you are reading this, you are very likely among
    the top 10% most affluent individuals of the world.  The remaining 90%, 
    whether located in your own community or abroad, have critical needs.  A 
    portion of all sales generated by LeaseHood.com is contributed directly to 
    organizations that help sustain the very essentials of life that we, the 
    10%, enjoy without a second thought.  Living Water International is a 
    non-profit organization founded upon the principle of providing clean 
    drinking water for disadvantaged regions of the world, in the spirit of 
    compassion.  Its objective ensures that donated energy and resources result
    in sustainable water systems that meet the long-term needs of 
    underdeveloped communities.  Habitat for Humanity is a nonprofit ministry 
    founded on the conviction that every man, woman and child should have a 
    decent, safe and affordable place to live, regardless of race or religion.  
    LeaseHood feels fortunate to be able contribute to the needs of both 
    organizations.  Be assured that your participation is contributing to new 
    drinking water wells and new homes for those who are in critical need.  
    LeaseHood thanks you for supporting these honorable organizations!

</p>
</div>


<?php
	include 'Footer.php';
?>
